In [15]:
import pandas as pd

In [16]:
#This is the Richmond USGS Data gage
river_richmnd = pd.read_csv('JR_Richmond02037500.csv').dropna()

/Users/williampc/opt/anaconda3/envs/geop/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [17]:
#Hurricane data for the basin - Names of Relevant Storms - This will be used for getting the storms from the larger set
JR_stormnames = pd.read_csv('gis_match.csv')

In [18]:
# #plotting some data - Just the example from matplotlib Gallery, may use later to superimpose many different things

# import matplotlib
# import matplotlib.pyplot as plt
# import numpy as np

# # Data for plotting
# time = river_richmnd['Time']
# dischg = river_richmnd['discharge_cfs']

# fig, ax = plt.subplots()
# ax.plot(time, dischg)

# ax.set(xlabel='time (YY/mm/dd)', ylabel='discharge (cfs)',
#        title='James River at Richmond')
# ax.grid()

# #fig.savefig("test.png")
# plt.show()

In [19]:
# Bring in the Big HURDAT data, from 1950 forward (satellites and data quality, etc.)
HURDAT = pd.read_csv('hurdatcleanva_1950_present.csv')

In [20]:
VA_JR_stormmatch = JR_stormnames.merge(HURDAT)

In [21]:
# Now the common storms for the James Basin have been created. We now have time and storms together for the basin
#checking some things about the data
# How many unique storms within the basin since 1950? 62 here and 53 in the Data on the Coast.NOAA.gov's website. 
#I think we are close enough here, digging may show some other storms, but I think we have at least captured the ones 
#from NOAA
len(VA_JR_stormmatch['Storm Number'].unique())

62

In [22]:
#double ck the lat and long parameters -OK
print(VA_JR_stormmatch['Lat'].min(),
VA_JR_stormmatch['Lon'].min(),
VA_JR_stormmatch['Lat'].max(),
VA_JR_stormmatch['Lon'].max())

36.1 -83.7 39.9 -75.1

In [23]:
#Make a csv of this data
VA_JR_stormmatch.to_csv('storms_in_basin.csv', sep=',',encoding = 'utf-8')

In [24]:
VA_JR_stormmatch;

In [25]:
#names of storms 
len(VA_JR_stormmatch['Storm Number'].unique())
VA_JR_stormmatch['Storm Number'].unique()
numbers = VA_JR_stormmatch['Storm Number']

In [26]:
#grab a storm from this list and lok at the times
#Bill = pd.DataFrame(VA_JR_stormmatch['Storm Number'=='AL032003'])

Alma = VA_JR_stormmatch[(VA_JR_stormmatch["Storm Number"] == 'AL011970')]
Alma
#so this is the data for a storm named ##### that had a pth through the basin * BILL WAS A BACKDOOR Storm

   Storm Name Storm Number Storm Status   Lat   Lon          Time  Maxspeed
11       ALMA     AL011970           EX  36.5 -77.0  5/27/70 0:00        25
12       ALMA     AL011970           EX  37.0 -75.5  5/27/70 6:00        25
13       ALMA     AL011970           EX  36.5 -77.0  5/27/70 0:00        25
14       ALMA     AL011970           EX  37.0 -75.5  5/27/70 6:00        25

In [28]:
# plotting for the USGS river Gage data 
import matplotlib
import matplotlib.pyplot as plt
from climata.usgs import DailyValueIO
from datetime import datetime
from pandas.plotting import register_matplotlib_converters
import numpy as np

register_matplotlib_converters()
plt.style.use('ggplot')
plt.rcParams['figure.figsize'] = (20.0, 10.0)
# set parameters
nyears = 1
ndays = 365 * nyears
station_id = "02037500"
param_id = "00065"

datelist = pd.date_range(end=datetime.today(), periods=ndays).tolist()
#take an annual average for the river
si_annual_gage = 12*0.3048
#now for the storm - Florence    
from climata.usgs import InstantValueIO
data = InstantValueIO(
start_date="1970-05-24",
end_date="1971-06-04",
station_id="02037500",
parameter_id="00065",
station=station_id,
parameter=param_id,)
#create lists of date-flow values
for series in data:
    gage = [r[1] for r in series.data]
    si_gage = np.asarray(gage) * 0.3048
    dates = [r[0] for r in series.data]

plt.plot(dates, si_gage)
plt.axhline(y=si_annual_gage, color='r', linestyle='-')
plt.xlabel('Date')
plt.ylabel('Gage (m)')
plt.title("Hurricane Alma - 1970 (Gulf)")
plt.xticks(rotation='vertical')
plt.show()

NameError: name 'dates' is not defined

In [43]:
# now to merge the River Data with this James River Data
river_hurdatvrjr = VA_JR_stormmatch.merge(river_richmnd)

In [44]:
river_hurdatvrjr

,Storm Name,Storm Number,Storm Status,Lat,Lon,Time,Maxspeed,agency_cd,site_no,tz_cd,discharge_cfs,discharge_cfs_cd,gage_height_ft,gage_height_ft_cd
0,BILL,AL022015,LO,38.5,-83.7,6/20/15 18:00,15,USGS,2037500,EDT,2180.0,A,4.01,A
1,BILL,AL022015,LO,38.5,-83.7,6/20/15 18:00,15,USGS,2037500,EDT,2180.0,A,4.01,A
2,BILL,AL022015,LO,38.9,-81.3,6/21/15 0:00,15,USGS,2037500,EDT,2290.0,A,4.06,A
3,BILL,AL022015,LO,38.9,-81.3,6/21/15 0:00,15,USGS,2037500,EDT,2290.0,A,4.06,A
4,CINDY,AL032017,LO,38.9,-78.5,6/24/17 6:00,25,USGS,2037500,EDT,4730.0,A,5.00,A
5,CINDY,AL032017,LO,38.9,-78.5,6/24/17 6:00,25,USGS,2037500,EDT,4730.0,A,5.00,A
6,IRENE,AL092011,HU,36.7,-75.7,8/28/11 0:00,65,USGS,2037500,EDT,2860.0,A,4.30,A
7,IRENE,AL092011,HU,36.7,-75.7,8/28/11 0:00,65,USGS,2037500,EDT,2860.0,A,4.30,A
8,IRENE,AL092011,HU,36.7,-75.7,8/28/11 0:00,65,USGS,2037500,EDT,2860.0,A,4.30,A
9,MICHAEL,AL142018,EX,36.5,-77.7,10/12/18 0:00,50,USGS,2037500,EDT,11100.0,A,6.70,A
10,MICHAEL,AL142018,EX,36.5,-77.7,10/12/18 0:00,50,USGS,2037500,EDT,11100.0,A,6.70,A
11,ANA,AL012015,TD,36.2,-77.3,5/11/15 12:00,30,USGS,2037500,EDT,6310.0,A,5.46,A
12,ANA,AL012015,TD,36.2,-77.3,5/11/15 12:00,30,USGS,2037500,EDT,6310.0,A,5.46,A
13,ANA,AL012015,TD,36.2,-77.3,5/11/15 12:00,30,USGS,2037500,EDT,6310.0,A,5.46,A
14,ANA,AL012015,TD,37.0,-76.3,5/11/15 18:00,30,USGS,2037500,EDT,6240.0,A,5.44,A
15,ANA,AL012015,TD,37.0,-76.3,5/11/15 18:00,30,USGS,2037500,EDT,6240.0,A,5.44,A
16,ANA,AL012015,TD,37.0,-76.3,5/11/15 18:00,30,USGS,2037500,EDT,6240.0,A,5.44,A
17,ANA,AL012015,LO,38.1,-75.1,5/12/15 0:00,30,USGS,2037500,EDT,6170.0,A,5.42,A
18,ANA,AL012015,LO,38.1,-75.1,5/12/15 0:00,30,USGS,2037500,EDT,6170.0,A,5.42,A
19,ANA,AL012015,LO,38.1,-75.1,5/12/15 0:00,30,USGS,2037500,EDT,6170.0,A,5.42,A
20,ANDREA,AL012013,EX,37.4,-76.2,6/8/13 0:00,40,USGS,2037500,EDT,26200.0,A,9.62,A
21,ANDREA,AL012013,EX,37.4,-76.2,6/8/13 0:00,40,USGS,2037500,EDT,26200.0,A,9.62,A
22,FLORENCE,AL062018,TD,36.4,-82.6,9/17/18 6:00,25,USGS,2037500,EDT,5870.0,A,5.32,A
23,FLORENCE,AL062018,TD,36.4,-82.6,9/17/18 6:00,25,USGS,2037500,EDT,5870.0,A,5.32,A
24,FLORENCE,AL062018,EX,37.8,-82.0,9/17/18 12:00,25,USGS,2037500,EDT,6540.0,A,5.52,A
25,FLORENCE,AL062018,EX,37.8,-82.0,9/17/18 12:00,25,USGS,2037500,EDT,6540.0,A,5.52,A
26,FLORENCE,AL062018,EX,38.8,-82.0,9/17/18 18:00,25,USGS,2037500,EDT,9800.0,A,6.39,A
27,FLORENCE,AL062018,EX,38.8,-82.0,9/17/18 18:00,25,USGS,2037500,EDT,9800.0,A,6.39,A
28,FLORENCE,AL062018,EX,39.5,-80.5,9/18/18 0:00,25,USGS,2037500,EDT,16900.0,A,7.94,A
29,FLORENCE,AL062018,EX,39.5,-80.5,9/18/18 0:00,25,USGS,2037500,EDT,16900.0,A,7.94,A
30,HANNA,AL082008,TS,37.8,-76.7,9/6/08 18:00,45,USGS,2037500,EDT,3540.0,A,4.71,A
31,HANNA,AL082008,TS,37.8,-76.7,9/6/08 18:00,45,USGS,2037500,EDT,3540.0,A,4.71,A
32,NESTOR,AL162019,EX,37.0,-76.7,10/20/19 18:00,40,USGS,2037500,EDT,2290.0,A,4.07,A
33,NESTOR,AL162019,EX,37.0,-76.7,10/20/19 18:00,40,USGS,2037500,EDT,2290.0,A,4.07,A

In [31]:
# the above is because names are only retired if they are deadly. however we can use the storm number to distinguish
len(river_hurdatvrjr["Storm Number"].unique())

27

In [32]:
# we need to get this done storm by storm to see the discharge 10 days surrounding the storm's arrival.
# we  select Hurricane Florence as a test case for an Atlantic Storm